<br><br>

---

# ML ZOOMCAMP - INTRODUCTION TO NUMPY

---

<br><br>

>Lesson Topics:
>
>  - Creating arrays
>  - Multi-dimensional arrays
>  - Randomly generated arrays
>  - Element-wise operations
>     - Comparison operations
>     - Logical operations
>  - Summarizing operations

In [1]:
import numpy as np

<br><br>

## Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a_lst = [1, 2, 3, 5, 6]
a_lst

[1, 2, 3, 5, 6]

In [6]:
# Convert into a numpy array
arr = np.array(a_lst)
arr

array([1, 2, 3, 5, 6])

In [7]:
# access the third value of the array
arr[2]

np.int64(3)

In [8]:
# assign a new value on third element of the array
arr[2] = 369
arr

array([  1,   2, 369,   5,   6])

<br>

---

In [9]:
# create an array of consecutive values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 13)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
np.arange(5, 100, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

<br>

---

In [12]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

<br>

---

## Multi-dimensional Arrays

In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# accessing individual values
m[0, 1]

np.int64(2)

In [18]:
# assigning a new value to m
m[1, 1] = 3333
m

array([[   1,    2,    3],
       [   4, 3333,    6],
       [   7,    8,    9]])

In [19]:
# accessing the 1st row
m[0]

array([1, 2, 3])

In [20]:
m[2]

array([7, 8, 9])

In [21]:
# re-writting the whole row
m[1] = [369, 693, 936]
m

array([[  1,   2,   3],
       [369, 693, 936],
       [  7,   8,   9]])

<br>

---

In [22]:
# accessing the 2nd column
m[:, 1]

array([  2, 693,   8])

In [23]:
m[:, 0]

array([  1, 369,   7])

In [24]:
# re-writting the whole 3rd column
m[:, 2] = [0, 0, 0]
m

array([[  1,   2,   0],
       [369, 693,   0],
       [  7,   8,   0]])

<br><br>

---

## Randomly Generated Arrays

In [25]:
# 3 Random values from 0 to 1 (uniform distribution)
a = np.random.rand(3)
a

array([0.79514676, 0.7624314 , 0.931208  ])

In [26]:
# 5x2 Random values (uniform distribution)
b = np.random.rand(5, 2)
b

array([[0.28165084, 0.48837905],
       [0.56777275, 0.28801391],
       [0.93403875, 0.19163379],
       [0.51299905, 0.60648326],
       [0.64762938, 0.45863388]])

In [27]:
# Now let's confirm the shape of our random values
print(f" - Shape of a:{a.shape}  \n - Shape of b:{b.shape}")

 - Shape of a:(3,)  
 - Shape of b:(5, 2)


<br>

---

In [28]:
# to get the same random values every time, we need to set a seed (uniform distribution)
np.random.seed(3)
np.random.rand(5, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

In [29]:
# if we ask for another random values, with the same seed. we'll get the same matrix of random values
# (uniform distribution)
np.random.seed(3)
np.random.rand(5, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

In [30]:
# Now we create random values from a "Standard Normal Distribution"
np.random.seed(3)
np.random.randn(5, 2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068],
       [-0.04381817, -0.47721803]])

In [31]:
# Random values from a "Standard Normal Distribution"
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

<br>

---

In [32]:
# Random integer values from a "Discrete Uniform Distribution"
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [33]:
# Random integer values from a "Discrete Uniform Distribution"
np.random.seed(2)
np.random.randint(low=0, high=100, size=(2, 5))

array([[40, 15, 72, 22, 43],
       [82, 75,  7, 34, 49]])

In [34]:
# Random integer values from a "Discrete Uniform Distribution"
np.random.seed(2)
np.random.randint(low=0, high=100, size=(3, 5))

array([[40, 15, 72, 22, 43],
       [82, 75,  7, 34, 49],
       [95, 75, 85, 47, 63]])

- Notice that If we use the same **random seed**, in this case `np.random.seed(2)`. but we change the size of the random integers, **we always get the same first ten values.**

<br><br>

---

## Element-wise Operations

In [35]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
# if we need to increase all array-values by the same amount, we can simple add the array by the desired value.
a + 3

array([3, 4, 5, 6, 7])

In [37]:
a * 3

array([ 0,  3,  6,  9, 12])

In [38]:
a / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [39]:
# therefore we can implement more complex math operations

b = (2 + (a ** 2) * 2) / 2
b

array([ 1.,  2.,  5., 10., 17.])

In [40]:
c = a + b
c

array([ 1.,  3.,  7., 13., 21.])

<br><br>

---

## Comparison Operations

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
a >= 2

array([False, False,  True,  True,  True])

In [43]:
a != 2

array([ True,  True, False,  True,  True])

<br>

---

In [44]:
c = b/2
c

array([0.5, 1. , 2.5, 5. , 8.5])

In [45]:
print(f'Array 1: {a}\nArray 2: {c}')

Array 1: [0 1 2 3 4]
Array 2: [0.5 1.  2.5 5.  8.5]


In [46]:
# we can compare arrays
a == c

array([False,  True, False, False, False])

In [47]:
# What values of array "a" is equal to array "c"?
a[a==c]

array([1])

In [48]:
# What values of array "c" are greater than "a"?
c[c > a]

array([0.5, 2.5, 5. , 8.5])

<br><br>

---

## Summarizing Operations

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a.min()

np.int64(0)

In [51]:
a.max()

np.int64(4)

In [52]:
a.sum()

np.int64(10)

In [53]:
a.mean()

np.float64(2.0)

In [54]:
a.std()

np.float64(1.4142135623730951)

In [55]:
a.var()

np.float64(2.0)

<br>

---

This operations can also be calculated on `Multi-dimensional Arrays`

In [56]:
m

array([[  1,   2,   0],
       [369, 693,   0],
       [  7,   8,   0]])

In [57]:
m.min()

np.int64(0)

In [58]:
m.max()

np.int64(693)

In [59]:
m.sum()

np.int64(1080)

In [60]:
m.mean()

np.float64(120.0)

In [61]:
m.std()

np.float64(232.6007547518088)

In [62]:
m.var()

np.float64(54103.11111111111)