<br><br>

---

# ML ZOOMCAMP - LINEAR ALGEBRA REFRESHER

---

<br><br>

>Lesson Topics:
>
>  - Vector Operations
>  - Multiplication
>     - Vector-Vector Multiplication
>     - Matrix-Vector Multiplication
>     - Matrix-Matrix Multiplication
>  - Identity Matrix
>  - Inverse Matrix

In [1]:
import numpy as np

<br><br>

---

# 1. Vector Operations

In [2]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

print(f'  - Vector u: {u}\n  - Vector v: {v}')

  - Vector u: [2 4 5 6]
  - Vector v: [1 0 0 2]


<br><br>

---


# 2. `Vector`-`Vector` Multiplication (*dot product*)



Unlike matrix multiplication, "multiplying two vectors" is **ambiguous** — it refers to two completely different operations depending on the orientation of the operands. Both reduce to the same underlying rule (rows times columns), but they produce results of very different shapes.

| Operation | Operand shapes | Result | Produces |
|---|---|---|---|
| **Inner product** (dot) | $(1 \times n)(n \times 1)$ | $1 \times 1$ | a **scalar** |
| **Outer product** | $(m \times 1)(1 \times n)$ | $m \times n$ | a **matrix** |

<br><br>


---

<span style='color:red'>
    
## 2.1. Inner Product (Dot Product)</span>

A row vector times a column vector of the **same length** $n$. The result is a single scalar.

$$
\mathbf{a}^\top \mathbf{b} = \sum_{i=1}^{n} a_i\, b_i
$$

**Compatibility rule**: both vectors must have the same number of elements $n$.

$$
\underbrace{\mathbf{a}^\top}_{1 \times n} \; \underbrace{\mathbf{b}}_{n \times 1} = \underbrace{c}_{1 \times 1}
$$

<br>

<span style='color:red'>
    
### Geometric interpretation (the *why*)</span>

The dot product also equals the product of the two vectors' magnitudes and the cosine of the angle $\theta$ between them:

$$
\mathbf{a}^\top \mathbf{b} = \|\mathbf{a}\|\, \|\mathbf{b}\| \cos\theta
$$

This is why the dot product measures **alignment**: it's positive when vectors point in similar directions, zero when they're orthogonal ($\theta = 90^\circ$), and negative when they point opposite ways. This single fact underlies cosine similarity, projections, and why orthogonality shows up everywhere in ML.

<br>

<span style='color:red'>
    
### Key properties</span>

- **Commutative**: $\mathbf{a}^\top \mathbf{b} = \mathbf{b}^\top \mathbf{a}$
- **Self dot product gives squared norm**: $\mathbf{a}^\top \mathbf{a} = \|\mathbf{a}\|^2$
- **Orthogonality test**: $\mathbf{a}^\top \mathbf{b} = 0 \iff \mathbf{a} \perp \mathbf{b}$

<br>

<span style='color:red'>
    
### Numerical example</span>

$$
\mathbf{a} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
$$

$$
\mathbf{a}^\top \mathbf{b} = (1)(4) + (2)(5) + (3)(6) = 4 + 10 + 18 = 32
$$

<br><br>

---

<span style='color:red'>

## 2.2. Outer Product</span>

A column vector times a row vector. The lengths do **not** need to match, and the result is a full matrix.

$$
\mathbf{a}\mathbf{b}^\top = C, \qquad c_{ij} = a_i\, b_j
$$

**Shapes**: if $\mathbf{a}$ has $m$ elements and $\mathbf{b}$ has $n$ elements, the result is $m \times n$.

$$
\underbrace{\mathbf{a}}_{m \times 1} \; \underbrace{\mathbf{b}^\top}_{1 \times n} = \underbrace{C}_{m \times n}
$$

<br>

<span style='color:red'>
    
### Key property</span>

- **Not commutative**: $\mathbf{a}\mathbf{b}^\top \neq \mathbf{b}\mathbf{a}^\top$. The two results are transposes of each other (and have swapped shapes $m \times n$ vs. $n \times m$).
- Every outer product has **rank 1** — every column is a scalar multiple of $\mathbf{a}$.

<br>

<span style='color:red'>
    
### Numerical example</span>

$$
\mathbf{a} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}_{3 \times 1}, \quad
\mathbf{b} = \begin{bmatrix} 4 \\ 5 \end{bmatrix}_{2 \times 1}
$$

$$
\mathbf{a}\mathbf{b}^\top =
\begin{bmatrix} (1)(4) & (1)(5) \\ (2)(4) & (2)(5) \\ (3)(4) & (3)(5) \end{bmatrix}
= \begin{bmatrix} 4 & 5 \\ 8 & 10 \\ 12 & 15 \end{bmatrix}_{3 \times 2}
$$

<br><br>

---

<span style='color:red'>

## 2.3. A third thing to not confuse: element-wise (Hadamard) product</span>

Neither of the above is the same as the **element-wise product**, which multiplies two vectors of the **same length** entry by entry and returns a vector (not a scalar, not a matrix):

$$
(\mathbf{a} \odot \mathbf{b})_i = a_i\, b_i
$$

$$
\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \odot \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
= \begin{bmatrix} 4 \\ 10 \\ 18 \end{bmatrix}
$$

Note the dot product is just the element-wise product **followed by a sum** of its entries.

<br><br>

In [3]:
# Constructing our dot product function
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result += u[i] * v[i]
    
    return result

In [4]:
# Let's calculate the dot product between u and v
vector_vector_multiplication(u, v)

np.float64(14.0)

In [5]:
# now its time to use numpy to make the same calculation

u.dot(v)

np.int64(14)

<br><br>

---


# 3. `Matrix`-`Vector` Multiplication (*dot product*)


<span style='color:red'>

## Definition and compatibility condition</span>

Given a matrix $A$ of dimensions $m \times n$ and a column vector $\mathbf{x}$ of dimensions $n \times 1$, their product is a column vector $\mathbf{b}$ of dimensions $m \times 1$:

$$
A\mathbf{x} = \mathbf{b}
$$

**Compatibility rule**: the number of *columns* of $A$ must equal the number of *rows* (elements) of $\mathbf{x}$.

$$
\underbrace{A}_{m \times n} \; \underbrace{\mathbf{x}}_{n \times 1} = \underbrace{\mathbf{b}}_{m \times 1}
$$

The inner dimensions ($n$) "cancel"; the outer dimensions ($m$ and $1$) define the shape of the result.

<br><br>

<span style='color:red'>
    
## General equation (element by element)</span>

Each component $b_i$ of the resulting vector is computed as:

$$
b_i = \sum_{j=1}^{n} a_{ij}\, x_j \qquad \text{for } i = 1, 2, \dots, m
$$

<br><br>

<span style='color:red'>
    
## Two interpretations of the same computation

### 3.1. Row view — dot product</span>

Each element of $\mathbf{b}$ is the dot product between a row of $A$ and the vector $\mathbf{x}$:

$$
A\mathbf{x} =
\begin{bmatrix} \text{---} & \mathbf{a}_1^\top & \text{---} \\[4pt] \text{---} & \mathbf{a}_2^\top & \text{---} \\ & \vdots & \end{bmatrix}
\mathbf{x} =
\begin{bmatrix} \mathbf{a}_1^\top \mathbf{x} \\[4pt] \mathbf{a}_2^\top \mathbf{x} \\ \vdots \end{bmatrix}
$$

<span style='color:red'>
    
### 3.2. Column view — linear combination</span>

The result is a linear combination of the columns of $A$, where the weights are the elements of $\mathbf{x}$:

$$
A\mathbf{x} = x_1 \mathbf{c}_1 + x_2 \mathbf{c}_2 + \cdots + x_n \mathbf{c}_n
$$

where $\mathbf{c}_j$ is the $j$-th column of $A$.

> This second view is the most powerful geometrically: multiplying $A$ by $\mathbf{x}$ means **mixing the columns of $A$ using the elements of $\mathbf{x}$ as weights**. It is the foundation for understanding the column space and why $A\mathbf{x} = \mathbf{b}$ has a solution only if $\mathbf{b}$ lives in the space spanned by the columns of $A$.

<br><br>

In [6]:
# Matrix
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])

# Vector
v = np.array([1, 0, 0, 2])

print(f' - Matrix:\n{U}\n\n - Vector:\n{v}')

 - Matrix:
[[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]

 - Vector:
[1 0 0 2]


<br><br>

Manual Calculation of `dot product` between Matrix an a vector

In [7]:
# Let's define our Matrix-Vector Multiplication
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [8]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

<br><br>

Numpy `dot product` Calculation between a matrix and a vector

In [9]:
# NOTE: Matrix should always be specified before `.dot()` numpy function
U.dot(v)

array([14,  5,  5])

In [10]:
# If we do it all the way around. We'll get a ValueError
#v.dot(U)

<br><br>

---


# 4. `Matrix`-`Matrix` Multiplication (*dot product*)


---

<br><br>

<span style='color:red'>

## Definition and compatibility condition</span>

Given a matrix $A$ of dimensions $m \times n$ and a matrix $B$ of dimensions $n \times p$, their product is a matrix $C$ of dimensions $m \times p$:

$$
AB = C
$$

**Compatibility rule**: the number of *columns* of $A$ must equal the number of *rows* of $B$.

$$
\underbrace{A}_{m \times n} \; \underbrace{B}_{n \times p} = \underbrace{C}_{m \times p}
$$

The inner dimensions ($n$) must match and "cancel"; the outer dimensions ($m$ and $p$) define the shape of the result.

<span style='color:orange'>
    
> **Note on terminology**: this is the standard matrix product (the "dot" / `@` product), *not* element-wise multiplication. Element-wise (Hadamard) multiplication requires both matrices to have the *same* shape and multiplies entry by entry — that's NumPy's `*` operator. The matrix product described here is NumPy's `@` operator.</span>

<br><br>

<span style='color:red'>
    
## General equation (element by element)</span>

Each entry $c_{ij}$ of the resulting matrix is the dot product between row $i$ of $A$ and column $j$ of $B$:

$$
c_{ij} = \sum_{k=1}^{n} a_{ik}\, b_{kj} \qquad \text{for } i = 1, \dots, m \;\text{ and }\; j = 1, \dots, p
$$

<br><br>

<span style='color:red'>
    
## Three interpretations of the same computation

<br>

### 4.1. Entry view — dot products</span>

Every entry $c_{ij}$ is the dot product of the $i$-th row of $A$ with the $j$-th column of $B$:

$$
C = \begin{bmatrix} \mathbf{a}_1^\top \mathbf{b}_1 & \mathbf{a}_1^\top \mathbf{b}_2 & \cdots \\[4pt] \mathbf{a}_2^\top \mathbf{b}_1 & \mathbf{a}_2^\top \mathbf{b}_2 & \cdots \\ \vdots & \vdots & \ddots \end{bmatrix}
$$

<br>

<span style='color:red'>

### 4.2. Column view — each column of $C$ is a matrix-vector product</span>

The $j$-th column of $C$ is $A$ times the $j$-th column of $B$:

$$
C = A\begin{bmatrix} \mathbf{b}_1 & \mathbf{b}_2 & \cdots & \mathbf{b}_p \end{bmatrix}
= \begin{bmatrix} A\mathbf{b}_1 & A\mathbf{b}_2 & \cdots & A\mathbf{b}_p \end{bmatrix}
$$

This connects directly to what you just learned: matrix-matrix multiplication is just **matrix-vector multiplication applied to each column of $B$ in turn**.

<br>

<span style='color:red'>
    
### 4.3. Row view — each row of $C$ is a vector-matrix product</span>

Symmetrically, the $i$-th row of $C$ is row $i$ of $A$ times the full matrix $B$:

$$
C = \begin{bmatrix} \mathbf{a}_1^\top B \\[4pt] \mathbf{a}_2^\top B \\ \vdots \end{bmatrix}
$$


<br><br>

<span style='color:red'>
    
## Numerical example</span>

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}_{2\times 3}, \qquad
B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}_{3\times 2}
$$

**Entry view:**

$$
C = \begin{bmatrix}
(1)(7)+(2)(9)+(3)(11) & (1)(8)+(2)(10)+(3)(12) \\
(4)(7)+(5)(9)+(6)(11) & (4)(8)+(5)(10)+(6)(12)
\end{bmatrix}
= \begin{bmatrix} 58 & 64 \\ 139 & 154 \end{bmatrix}
$$

**Column view (same result):** the first column of $C$ is $A\mathbf{b}_1$ with $\mathbf{b}_1 = [7, 9, 11]^\top$, and the second is $A\mathbf{b}_2$ with $\mathbf{b}_2 = [8, 10, 12]^\top$.

$$
A\mathbf{b}_1 = \begin{bmatrix} 58 \\ 139 \end{bmatrix}, \qquad
A\mathbf{b}_2 = \begin{bmatrix} 64 \\ 154 \end{bmatrix}
$$


<br><br>

<span style='color:red'>

## Key properties (and one warning)</span>

- **Not commutative**: in general $AB \neq BA$. Often $BA$ isn't even defined (dimensions may not match), and even when both exist they're usually different matrices.
  
- **Associative**: $(AB)C = A(BC)$.

- **Distributive**: $A(B + C) = AB + AC$.

- **Identity**: $AI = IA = A$, where $I$ is the identity matrix of the appropriate size.

<br><br>

In [11]:
V = np.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1], [2, 1, 0]])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [12]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [13]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result [:, i] = Uvi

    return result

In [14]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [15]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

<br><br>

---


# 5. `Identity Matrix`


<br><br>

<span style='color:red'>

## Definition</span>

The identity matrix $I_n$ is the **square** $n \times n$ matrix with ones on the main diagonal and zeros everywhere else:

$$
I_n = \begin{bmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 1
\end{bmatrix}_{n \times n}
$$

When the size is clear from context, it's written simply as $I$.


<br>

<span style='color:red'>
    
## The defining property: multiplicative identity</span>

The identity matrix is the matrix equivalent of the number $1$. Multiplying any matrix $A$ by $I$ leaves it **unchanged**:

$$
AI = IA = A
$$

A size subtlety worth keeping in mind: if $A$ is $m \times n$, then the left and right identities have *different* sizes:

$$
\underbrace{I_m}_{m \times m} A = A = A \underbrace{I_n}_{n \times n}
$$

For square $A$, both are the same $I_n$, and $I$ is one of the few matrices that **commutes** with every other matrix of its size.

<br>

<span style='color:red'>
    
## Geometric interpretation (the *why*)</span>

As a linear transformation, $I$ is the **identity transformation**: it maps every vector to itself.

$$
I\mathbf{x} = \mathbf{x} \quad \text{for every } \mathbf{x}
$$

This follows directly from the column view you already learned: the columns of $I_n$ are exactly the standard basis vectors $\mathbf{e}_1, \mathbf{e}_2, \dots, \mathbf{e}_n$. So $I\mathbf{x}$ is the linear combination that rebuilds $\mathbf{x}$ from its own coordinates — it "does nothing," which is precisely why it's the identity.

$$
I_3 = \begin{bmatrix} \mathbf{e}_1 & \mathbf{e}_2 & \mathbf{e}_3 \end{bmatrix}
= \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

<br>

<span style='color:red'>

## Connection to the matrix inverse</span>

The identity is what *defines* the **inverse** of a square matrix. $A^{-1}$ is the matrix that, multiplied by $A$, returns the identity:

$$
A A^{-1} = A^{-1} A = I
$$

This is the direct analogue of $x \cdot x^{-1} = 1$ for real numbers, and it's the reason the identity matrix is central to solving linear systems $A\mathbf{x} = \mathbf{b}$.

<br>

<span style='color:red'>
    
## Key properties</span>

- **Symmetric**: $I^\top = I$

- **Idempotent**: $I^k = I$ for any positive integer $k$ (multiplying $I$ by itself always gives $I$)

- **Its own inverse**: $I^{-1} = I$

- **Determinant**: $\det(I) = 1$

- **Trace**: $\operatorname{tr}(I_n) = n$

- **All eigenvalues equal 1**


<br>

<span style='color:red'>
    
## Numerical example</span>

Multiplying a matrix by $I$ returns it unchanged:

$$
\begin{bmatrix} 2 & 5 \\ 7 & 3 \end{bmatrix}
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
= \begin{bmatrix} 2 & 5 \\ 7 & 3 \end{bmatrix}
$$

And acting on a vector, it leaves it in place:

$$
\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
\begin{bmatrix} 8 \\ 9 \\ 4 \end{bmatrix}
= \begin{bmatrix} 8 \\ 9 \\ 4 \end{bmatrix}
$$

<br><br>

In [16]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>

---

In [17]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [18]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

<br>

---

In [19]:
U.T

array([[2, 1, 3],
       [4, 2, 1],
       [5, 1, 2],
       [6, 2, 1]])

In [20]:
U.T.dot(I)

array([[2., 1., 3.],
       [4., 2., 1.],
       [5., 1., 2.],
       [6., 2., 1.]])

<br><br>

---


# 6. `Matrix Inverse`


<br><br>

---

<span style='color:red'>
    
## Definition</span>

The inverse of a **square** matrix $A$ (size $n \times n$) is the matrix $A^{-1}$ that returns the identity when multiplied by $A$ — from either side:

$$
A A^{-1} = A^{-1} A = I
$$

This is the direct analogue of the reciprocal of a number: just as $x \cdot x^{-1} = 1$ for any nonzero real number, $A^{-1}$ is the matrix that "undoes" $A$ and lands back on the multiplicative identity $I$.

<br>

<span style='color:red'>
    
## When does an inverse exist?</span>

**Only square matrices can have an inverse** — but being square is *necessary, not sufficient*. A square matrix is invertible (also called **non-singular**) if and only if its **determinant is nonzero**:

$$
A^{-1} \text{ exists} \iff \det(A) \neq 0
$$

If $\det(A) = 0$, the matrix is called **singular** and has no inverse. These conditions are all equivalent ways of saying the same thing:

- $\det(A) \neq 0$
- The columns of $A$ are **linearly independent**
- $A$ has **full rank** ($\operatorname{rank}(A) = n$)
- $A\mathbf{x} = \mathbf{0}$ has only the trivial solution $\mathbf{x} = \mathbf{0}$

<br>

<span style='color:red'>
    
## The 2×2 formula</span>

For a $2 \times 2$ matrix there's a closed-form shortcut worth memorizing:

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
\quad\Longrightarrow\quad
A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
= \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

The recipe: **swap** the diagonal entries, **negate** the off-diagonal entries, and **divide** by the determinant. Notice the inverse blows up (division by zero) exactly when $ad - bc = 0$ — which is precisely the singular case.

<br>

<span style='color:red'>
    
## Geometric interpretation (the *why*)</span>

As a linear transformation, $A$ stretches, rotates, or shears space. $A^{-1}$ is the transformation that **reverses** that action, sending every transformed vector back to where it started:

$$
\text{if } \mathbf{y} = A\mathbf{x}, \quad \text{then } \mathbf{x} = A^{-1}\mathbf{y}
$$

This is also why singular matrices *can't* be inverted. The determinant measures how much the transformation scales volume; $\det(A) = 0$ means $A$ collapses space onto a lower-dimensional subspace (it squashes at least one dimension flat). Once that dimension is flattened, the information is gone — there's no way to reconstruct the original, so no inverse can exist.

<br>

<span style='color:red'>
    
## Connection to solving linear systems</span>

This is where the inverse earns its importance. Any linear system

$$
A\mathbf{x} = \mathbf{b}
$$

can be solved — in theory — by multiplying both sides by $A^{-1}$:

$$
A^{-1}A\mathbf{x} = A^{-1}\mathbf{b} \quad\Longrightarrow\quad I\mathbf{x} = A^{-1}\mathbf{b} \quad\Longrightarrow\quad \mathbf{x} = A^{-1}\mathbf{b}
$$

(See the practical warning in the code section below — this is the *conceptual* solution, not the *computational* one you should actually use.)

<br>

<span style='color:red'>
    
## Key properties</span>

- **Inverse of the inverse**: $(A^{-1})^{-1} = A$

- **Product rule (order reverses!)**: $(AB)^{-1} = B^{-1}A^{-1}$ — note the flip

- **Transpose**: $(A^\top)^{-1} = (A^{-1})^\top$

- **Scalar**: $(cA)^{-1} = \frac{1}{c}A^{-1}$ for a nonzero scalar $c$

- **Determinant**: $\det(A^{-1}) = \dfrac{1}{\det(A)}$

<br>

<span style='color:red'>
    
## Numerical example</span>

$$
A = \begin{bmatrix} 4 & 7 \\ 2 & 6 \end{bmatrix}, \qquad
\det(A) = (4)(6) - (7)(2) = 24 - 14 = 10
$$

Applying the formula:

$$
A^{-1} = \frac{1}{10} \begin{bmatrix} 6 & -7 \\ -2 & 4 \end{bmatrix}
= \begin{bmatrix} 0.6 & -0.7 \\ -0.2 & 0.4 \end{bmatrix}
$$

Verification that $AA^{-1} = I$:

$$
\begin{bmatrix} 4 & 7 \\ 2 & 6 \end{bmatrix}
\begin{bmatrix} 0.6 & -0.7 \\ -0.2 & 0.4 \end{bmatrix}
= \begin{bmatrix} 2.4 - 1.4 & -2.8 + 2.8 \\ 1.2 - 1.2 & -1.4 + 2.4 \end{bmatrix}
= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$


<br><br>

In [21]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [22]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

<br><br>

---

In [23]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

<br><br>

---

In [24]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])